packages:
  - apps/*
  - services/*
  - packages/*
  - providers/*

overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1

allowBuilds:
  '@alicloud/openapi-core': false
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  protobufjs: false
