import { Catch, type ArgumentsHost, type ExceptionFilter } from '@nestjs/common';
import type { FastifyReply } from 'fastify';

export const IAM_HTTP_STABLE_STATUS_CODES: Readonly<Record<string, number>> = Object.freeze(Object.assign(
  Object.create(null) as Record<string, number>,
  Object.fromEntries([
  ...codes(400, [
    'INVALID_REQUEST', 'INVALID_ADMIN_ID', 'INVALID_ADMIN_SESSION_ID', 'INVALID_ADMIN_SESSION_FAMILY_ID',
    'INVALID_MFA_CHALLENGE_ID', 'INVALID_RECOVERY_CODE_ID', 'INVALID_RECOVERY_GENERATION_ID',
    'INVALID_AUDIT_ACTOR_ID', 'INVALID_AUDIT_CAUSATION_ID', 'INVALID_AUDIT_CONTEXT',
    'INVALID_AUDIT_CORRELATION_ID', 'INVALID_AUDIT_ID', 'INVALID_AUDIT_QUERY', 'INVALID_AUDIT_TRACE_ID',
    'INVALID_DATA_SCOPE', 'INVALID_DEVICE_NAME', 'INVALID_PASSWORD', 'INVALID_PERMISSION_KEYS',
    'INVALID_ROLE_DESCRIPTION', 'INVALID_ROLE_ID', 'INVALID_ROLE_NAME', 'INVALID_ROLE_QUERY',
    'INVALID_ROLE_VERSION', 'INVALID_UUID_V7', 'INVALID_UUID_V7_TIMESTAMP',
    'INVALID_PENDING_CLEANUP_LIMIT', 'ROLE_ASSIGNMENT_PRECONDITION_REQUIRED',
  ]),
  ...codes(401, [
    'INVALID_ADMIN_ACCESS_TOKEN', 'ADMIN_ACCESS_SESSION_INACTIVE', 'INVALID_ADMIN_PRINCIPAL',
    'UNTRUSTED_ADMIN_PRINCIPAL', 'INVALID_BOOTSTRAP_PROOF', 'INVALID_CREDENTIALS', 'INVALID_MFA',
    'INVALID_REFRESH_TOKEN', 'SESSION_REVOKED', 'SESSION_EXPIRED', 'ADMIN_SESSION_INACTIVE',
    'MFA_CHALLENGE_EXPIRED', 'MFA_REPLAY_DETECTED', 'REFRESH_REUSE_DETECTED',
  ]),
  ...codes(403, [
    'ADMIN_AUTHORIZATION_DENIED', 'CAPABILITY_CEILING_EXCEEDED', 'PROTECTED_ROLE_ASSIGNMENT_DENIED',
    'LAST_SUPER_ADMIN_PROTECTED', 'PROTECTED_ROLE', 'ADMIN_NOT_ACTIVE', 'MFA_NOT_ENROLLED',
    'ROLE_MUTATION_DENIED', 'ROLE_ASSIGNMENT_DENIED',
  ]),
  ...codes(404, ['ADMIN_NOT_FOUND', 'ROLE_NOT_FOUND', 'PERMISSION_NOT_FOUND']),
  ...codes(409, [
    'MFA_ALREADY_ENABLED', 'MFA_CHALLENGE_USED', 'MFA_ENROLLMENT_CONFLICT', 'MFA_ENROLLMENT_NOT_STARTED',
    'MFA_FINALIZATION_CONFLICT', 'MFA_RESERVATION_CONFLICT', 'REFRESH_FINALIZATION_CONFLICT',
    'REFRESH_IN_PROGRESS', 'ROLE_VERSION_CONFLICT', 'ROLE_NAME_CONFLICT', 'ROLE_ASSIGNED',
    'ROLE_NOT_ASSIGNED', 'SUPER_ADMIN_ALREADY_BOOTSTRAPPED',
  ]),
  ...codes(429, ['AUTH_RATE_LIMITED', 'MFA_CHALLENGE_LOCKED']),
  ...codes(503, [
    'CLOUD_SDK_UNAVAILABLE', 'DATABASE_CLOCK_UNAVAILABLE', 'ADMIN_DISABLE_COORDINATOR_UNAVAILABLE',
    'ADMIN_DISABLE_STATE_MISMATCH', 'ADMIN_SESSION_FINALIZATION_FAILED', 'ADMIN_TOKEN_ISSUANCE_FAILED',
    'ROLE_PERSISTENCE_FAILED', 'RECOVERY_CODE_GENERATION_FAILED', 'INSUFFICIENT_RECOVERY_CODE_ENTROPY',
    'INSUFFICIENT_TOKEN_ENTROPY', 'INSUFFICIENT_UUID_V7_ENTROPY', 'INVALID_DUMMY_PASSWORD_HASH',
    'INVALID_RECOVERY_CODE_PEPPER', 'SECRET_DECRYPTION_FAILED', 'INVALID_KMS_SIGNATURE',
    'INVALID_KMS_CONFIGURATION', 'INVALID_KMS_HMAC_CONFIGURATION', 'INVALID_KMS_HMAC_KEYRING',
    'INVALID_KMS_IDENTITY', 'INVALID_KMS_KEYRING', 'INVALID_KMS_SIGNER_CONFIGURATION',
    'UNSUPPORTED_KMS_IDENTITY', 'UNVERSIONED_KMS_HMAC_KEY_REFERENCE', 'UNVERSIONED_KMS_KEY_REFERENCE',
    'UNVERSIONED_KMS_SIGNING_KEY_REFERENCE', 'MEMORY_DISABLE_PARTICIPANT_ALREADY_REGISTERED',
  ]),
  ]),
));

@Catch()
export class IamHttpExceptionFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost): void {
    const reply = host.switchToHttp().getResponse<FastifyReply>();
    const code = stableCode(exception);
    const status = Object.hasOwn(IAM_HTTP_STABLE_STATUS_CODES, code)
      ? (IAM_HTTP_STABLE_STATUS_CODES[code] ?? 500)
      : 500;
    reply.status(status).send({ code: status === 500 ? 'INTERNAL_SERVER_ERROR' : code });
  }
}

function codes(status: number, values: readonly string[]): Array<readonly [string, number]> {
  return values.map((code) => [code, status] as const);
}
function stableCode(error: unknown): string {
  if (!(error instanceof Error)) return 'INTERNAL_SERVER_ERROR';
  try {
    const code = Reflect.get(error, 'code') as unknown;
    return typeof code === 'string' ? code : 'INTERNAL_SERVER_ERROR';
  } catch {
    return 'INTERNAL_SERVER_ERROR';
  }
}
